name: SharpGLTF

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:        
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4      
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.x'
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test ./tests/TestAttachments.NUnit.Tests/TestAttachments.NUnit.Tests.csproj
      - if: runner.os == 'Windows'
        run: dotnet test ./tests/TestImages.Tests/TestImages.Tests.csproj
